import asyncio
import json
import os
import sys

import httpx

URL_READ = "http://127.0.0.1:8000/api/v1/hwpx/read"
URL_MODIFY = "http://127.0.0.1:8000/api/v1/hwpx/modify"
URL_OLLAMA = "http://localhost:11435/api/chat"


async def ask_ollama_for_modification(blocks: list) -> list:
    """Interacts with local Ollama to generate a modification payload."""
    # We will pass a sample of the blocks to the LLM so it's not overwhelmed
    blocks_text = json.dumps(blocks[:10], ensure_ascii=False, indent=2)

    prompt = f"""
다음은 HWPX 문서에서 추출한 텍스트 블록의 일부입니다:
{blocks_text}

이 문서에서 아무 텍스트나 하나 골라서, 해당 텍스트를 논리적인 문장으로 바꾸거나 특정한 단어로 수정하고 싶습니다.
아래의 JSON 배열 포맷에 맞추어, 정확히 어떤 `block_id`의 `target_text`(원본 텍스트 일부)를 어떤 `replace_text`(새로운 텍스트)로 변경할지 1개의 수정사항만 딱 JSON으로만 출력해주세요. 마크다운 백틱(```)이나 부가 설명은 절대 넣지 마세요.

형식:
[
  {{
    "block_id": "수정할블럭ID",
    "target_text": "원래있던텍스트의일부",
    "replace_text": "새롭게바꿀텍스트"
  }}
]
"""
    print("Requesting LLM modification from Ollama (localhost:11435)...")
    payload = {
        "model": "llama3.1",  # Default to a common model name, can be anything the user has installed
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful AI assistant that strictly returns valid JSON arrays without markdown block delimiters.",
            },
            {"role": "user", "content": prompt},
        ],
        "stream": False,
        "format": "json",
    }

    async with httpx.AsyncClient() as client:
        try:
            # We don't know the exact model name the user has, trying a generic approach or just 'qwen' or 'llama3' etc.
            # Assuming the user has a model. If it fails, they can change the model name in the script.
            # Usually `llama3.1` or `gemma2` or `mistral` are common. We'll use a placeholder 'llama3' for now.
            payload["model"] = "gemma3:12b"
            response = await client.post(URL_OLLAMA, json=payload, timeout=60.0)
            if response.status_code == 200:
                data = response.json()
                content = data.get("message", {}).get("content", "[]")
                print(f"LLM Response:\n{content}")

                # Parse JSON
                try:
                    mods = json.loads(content)
                    if isinstance(mods, dict):
                        mods = [mods]  # Wrap in list if it returned a single dict
                    return mods
                except json.JSONDecodeError:
                    print("Failed to parse LLM JSON response.")
                    return []
            else:
                print(f"Ollama error: {response.text}")
                return []
        except Exception as e:
            print(f"Error connecting to Ollama: {e}")
            return []


async def main():
    template_path = "../templates/공문 예시.hwpx"
    output_path = "../result/완성본_테스트.hwpx"

    # 1. 문서 구조 읽기
    print(f"1. {template_path} 구조 읽기 중...")
    if not os.path.exists(template_path):
        print(f"Error: Could not find {template_path}")
        sys.exit(1)

    print("Step 1: Reading File...")

    async with httpx.AsyncClient() as client:
        # Step 1: Read
        with open(template_path, "rb") as f:
            files = {"file": (os.path.basename(template_path), f, "application/octet-stream")}
            read_res = await client.post(URL_READ, files=files, timeout=10.0)

        if read_res.status_code != 200:
            print(f"Read API Failed: {read_res.text}")
            return

        read_data = read_res.json()
        blocks = read_data.get("blocks", [])

        if not blocks:
            print("No text blocks found in the document.")
            return

        # Step 2: LLM Call
        modifications = await ask_ollama_for_modification(blocks)
        if not modifications:
            print("No valid modifications generated by LLM.")
            return

        print("\nStep 3: Applying Modifications via Modify API...")
        modifications_json = json.dumps(modifications)

        # Step 3: Modify
        with open(template_path, "rb") as f:
            files = {"file": (os.path.basename(template_path), f, "application/octet-stream")}
            data = {"modifications": modifications_json}
            mod_res = await client.post(URL_MODIFY, files=files, data=data, timeout=10.0)

        if mod_res.status_code == 200:
            with open(output_path, "wb") as out_f:
                out_f.write(mod_res.content)
            print(f"SUCCESS: Saved modified file to {output_path}")
        else:
            print(f"Modify API Failed: {mod_res.text}")


if __name__ == "__main__":
    asyncio.run(main())
